<?php

namespace StockBundle\Repository;

use http\Env\Response;
use StockBundle\Entity\MouvementDuStock;
use StockBundle\Entity\Produit;

/**
 * MouvementDuStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementDuStockRepository extends \Doctrine\ORM\EntityRepository



{   public function updateProduit(MouvementDuStock $mouvementDuStock, $qte, $fk){

    if ($mouvementDuStock->getNatureMouvement()=='Entrée'){
        return $this->createQueryBuilder('p')
            ->update('StockBundle:produit','p')
            ->set('p.quantite', 'p.quantite + ?0')
            ->where('p.idProduit = ?1')
            ->setParameter(0,$qte)
            ->setParameter(1,$fk)
            ->getQuery()
            ->execute();

    }else {

        return $this->createQueryBuilder('p')
            ->update('StockBundle:produit','p')
            ->set('p.quantite', 'p.quantite - ?0')
            ->where('p.idProduit = ?1')
            ->setParameter(0,$qte)
            ->setParameter(1,$fk)
            ->getQuery()
            ->execute();
    }
}}