<?php

namespace StockBundle\Repository;

use StockBundle\Entity\Produit;

/**
 * MouvementDuStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementDuStockRepository extends \Doctrine\ORM\EntityRepository



{
public function qa(){

    $qb = $this->getEntityManager()
        ->createQuery("UPDATE StockBundle:produit p SET p.quantite=:qte WHERE p.idProduit=:fk")
        ->setParameters(array('qte' => 30, 'fk' => $mouvementDuStock->getFkProduit()))
        ->execute();
}public function qs(){

    $qb = $this->getEntityManager()
        ->createQuery("UPDATE StockBundle:produit p SET p.quantite=:qte WHERE p.idProduit=:fk")
        ->setParameters(array('qte' => 30, 'fk' => $mouvementDuStock->getFkProduit()))
        ->execute();
}
    public function qteup($qte, $fk)
    {
        $qb = $this->getEntityManager()
            ->createQuery("Select p.quantite from StockBundle:produit p WHERE p.idProduit=:fk")
            ->setParameter('fk', $fk);
        $res = mysql_result($qb,1);

        if ($res == 0) {
            $qb1 = $this->getEntityManager()
                ->createQuery("UPDATE StockBundle:produit p SET p.quantite=:qte WHERE p.idProduit=:fk")
                ->setParameters(array('qte' => $qte, 'fk' => $fk))
                ->execute();
        } else {
            $qb2 = $this->getEntityManager()
                ->createQuery("UPDATE StockBundle:produit p SET p.quantite=:qte WHERE p.idProduit=:fk")
                ->setParameters(array('qte' => $qte + $res, 'fk' => $fk))
                ->execute();


        }


    }

    public function qtechk($fk)
    {

        $qb = $this->getEntityManager()
            ->createQuery("Select p.quantite from StockBundle:produit p WHERE p.idProduit=:fk")
            ->setParameter('fk', $fk);
       $res = $qb->getResult();
        var_dump($res);
      echo  json_encode($res);

    }
}