<?php

namespace RHBundle\Repository;

/**
 * congeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class congeRepository extends \Doctrine\ORM\EntityRepository
{
}
