<?php

namespace RHBundle\Repository;

use Symfony\Component\HttpFoundation\Request;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{

}
