<?php

namespace EntrepotBundle\Repository;

/**
 * MouvementDuStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementDuStockRepository extends \Doctrine\ORM\EntityRepository
{
}
