<?php

namespace CommandeBundle\Repository;

/**
 * ProduitCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
