<?php

namespace TransporteurBundle\Repository;

/**
 * ContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratRepository extends \Doctrine\ORM\EntityRepository
{

    public function getContratByProp($id)
    {
        $qb=$this->getEntityManager()
            ->createQuery("select e.idEntrepot , u.id , c.datedeb , c.datefin , c.salaire , u.nom , u.prenom , e.entreprise from TransporteurBundle:contrat c JOIN c.FKiduser u JOIN c.FKidentrepot e where c.FKidentrepot IN ( select t.idEntrepot from EntrepotBundle:entrepot t where t.idUser=?1) ")
            ->setParameters(array(1=>$id));
        return $query = $qb->getResult();
    }

    public function updateContrat($dateDeb,$dateFin,$id)
    {
        $qb=$this->getEntityManager()
            ->createQuery("Update TransporteurBundle:contrat c SET c.datedeb=?1 and c.datefin=?2 where c.FKiduser=?3")
            ->setParameters(array(1=>$dateDeb,2=>$dateFin,3=>$id));
        return $query=$qb->getResult();
    }


}
