<?php

namespace TransporteurBundle\Repository;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLivraisonByUserNotD($id)
    {
        $qb=$this->getEntityManager()
            ->createQuery("select l from TransporteurBundle:livraison l where l.etatLivraison=?1 and l.fkUser=?2 ")
            ->setParameters(array(1=>'non livrée',2=>$id));
        return $query = $qb->getResult();
    }


    public function getLivraisonByUserD($id)
    {
        $qb=$this->getEntityManager()
            ->createQuery("select l from TransporteurBundle:livraison l where l.etatLivraison=?1 and l.fkUser=?2 ")
            ->setParameters(array(1=>'livrée',2=>$id));
        return $query = $qb->getResult();
    }

    public function updateLivStat($id)
    {
        $qb=$this->getEntityManager()
            ->createQuery("Update TransporteurBundle:livraison l SET l.etatLivraison=?1 where l.idLivraison=?2")
            ->setParameters(array(1=>'livrée',2=>$id));
        return $query=$qb->getResult();
    }

    public function getNbrLivraison($id)
    {
        $qb=$this->getEntityManager()
            ->createQuery(" select COUNT(l.etatLivraison) NBR from TransporteurBundle:livraison l where l.etatLivraison=?1 and l.fkUser=?2 ")
            ->setParameters(array(1=>'non livrée',2=>$id));
        return $query = $qb->getResult();

    }







}
