<?php

namespace GererEntrepotBundle\Repository;

/**
 * EntrepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepotRepository extends \Doctrine\ORM\EntityRepository
{
    public function afficherEtatALouer()
    {$qb=$this->getEntityManager()
              ->createQuery("select c from GererEntrepotBundle:Entrepot c where c.etat= 'A Louer'");

    return $query=$qb->getResult();

    }
}
